### ISSUE TITLE
openrazer-daemon running with debug log level

### ISSUE THREAD

**Issue by darix** [openrazer/OBS-packaging#6]
is this really necessary or can we lower that maybe?

**Comment by z3ntu** [comment]
The systemd service doesn't add the verbose parameter `-v` for openrazer-daemon since v2.8.0: https://github.com/openrazer/openrazer/commit/162ba7b7493929da0219ef6de9e562478551ccca

You can also check `~/.config/openrazer/razer.conf` if verbose logging is enabled there

**Comment by darix** [comment]
ah must have been from some testing in march last year.

I didnt create the file manually.
